---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 389
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}
    
---
apiVersion: v1
kind: Endpoints
metadata: 
  name: ldap-enpoints
subsets:
  - addresses:
      - ip: 192.xxx.xx.1
      - ip: 192.xxx.xx.2
      - ip: 192.xxx.xx.3
    ports:
      - port: 389
---
apiVersion: v1
kind: Service
metadata:
  name: ldap-enpoints
spec:
  ports:
  - port: 389
